

services:

  Preprocessor:
    image: shmuelblau/preprocessor:1
    container_name: preprocessor
    
    depends_on:
      - kafka

    environment:
       HOST: "kafka"
       PATH_DIR: "/app/podcasts"
       TOPIC_NAME : "Metadata_Muezzin"
       
       
     
    command: ["python" , "main.py"]
    volumes:
      - C:/podcasts:/app/podcasts
    networks:
      MuezzinProject:
# ------------------------------------------------------------------- 



# ------------------------------------------------------------------- 

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
        KAFKA_BROKER_CONNECT: "kafka:9092"
    depends_on:
      - kafka
    networks:
      MuezzinProject:

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true 
    networks:
      MuezzinProject:
# ------------------------------------------------------------------- 

# ------------------------------------------------------------------- 

  # mongodb:
  #   image: mongo:6.0
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: shmuel
  #     MONGO_INITDB_ROOT_PASSWORD: "1234"
  #     MONGO_INITDB_DATABASE: TextFeature
  #   volumes:
  #     - mongo-data:/data/db
     
  #   restart: unless-stopped
  #   networks:
  #     Models:

# ------------------------------------------------------------------- 



networks:
  
  MuezzinProject: