FROM python:3.10-slim

WORKDIR /app

COPY services/DataRetrieval/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY services/DataRetrieval .
COPY utils/decoretors /app/classes
COPY utils/elastic /app/classes


CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]