apiVersion: v1
kind: PersistentVolume
metadata:
  name: podcasts-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/C:/podcasts"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  podcasts-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi