apiVersion: apps/v1
kind: Deployment
metadata:
  name: DataRetrieval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DataRetrieval
  template:
    metadata:
      labels:
        app: DataRetrieval
    spec:
      containers:
        - name: DataRetrieval
          image: shmuelblau/dataretrieval:1
          
          command: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
          

---
apiVersion: v1
kind: Service
metadata:
  name: DataRetrieval-service
spec:
  selector:
    app: DataRetrieval
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30003
  type: NodePort      

      